---
# tasks file for ansible-role-module-marathon

- name: call marathon module
  marathon:
    marathon_url: "{{ item.marathon_url|default('https://dev-dcos-master.mgage.io/') }}"
    app_id: "{{ item.app_id|default(omit) }}"
    app_json: "{{ item.app_json|default(omit) }}"
  with_items: "{{ marathon_app|default([]) }}"
